import { resolve } from './store.js';
import type { OperatingContext, Rule, Target } from './types.js';

export type Proposal = { action?: 'start'|'stop'|'change'|'test'|'keep'|'send'|'publish'; target?: string; discount_pct?: number; free_shipping?: boolean; compare_at?: boolean; guarantee?: boolean; mentions_competitor?: boolean; uses_ugc?: boolean; audience?: string; channel?: string; claims?: string[]; text?: string };
const fields: Record<string, string> = { discount: 'discount_pct', free_shipping: 'free_shipping', compare_at: 'compare_at', guarantee: 'guarantee', mention_competitor: 'mentions_competitor', use_ugc: 'uses_ugc', target_audience: 'audience', send: 'channel' };
const compare = (op: string, expected: unknown, actual: unknown) => { const a: any = actual; return op === 'gt' ? a > (expected as any) : op === 'gte' ? a >= (expected as any) : op === 'lt' ? a < (expected as any) : op === 'lte' ? a <= (expected as any) : op === 'eq' ? a === expected : op === 'neq' ? a !== expected : op === 'in' ? Array.isArray(expected) && expected.includes(a) : op === 'not_in' ? Array.isArray(expected) && !expected.includes(a) : false; };
function scopeFor(ctx: OperatingContext, input: { targets?: string[]; proposal?: Proposal }) { const names = [...(input.targets ?? []), ...(input.proposal?.target ? [input.proposal.target] : []), ...(input.proposal?.channel ? [input.proposal.channel] : []), ...(input.proposal?.audience ? [input.proposal.audience] : [])]; const unique = [...new Set(names)]; const resolved = unique.map(n => resolve(ctx.targets, n)).filter((t): t is Target => !!t); const unresolved = unique.filter(n => !resolve(ctx.targets, n)); return { resolved, unresolved }; }
export function compileConstraints(ctx: OperatingContext, scope: Target[]) { const out: any[] = []; for (const target of scope) { const ds = ctx.history.filter(d => d.status === 'confirmed' && d.target === target.id).sort((a,b) => Date.parse(a.decided_at)-Date.parse(b.decided_at)); const d = ds.at(-1); if (!d) continue; const base = { target: target.id, since: d.decided_at, decision_id: d.id, lift_requires: 'a new confirmed operator decision on this target' }; if (d.action === 'stop' && d.outcome === 'negative') out.push({ ...base, constraint: 'no_start', reason: `operator stopped ${target.name} on ${d.decided_at.slice(0,10)}${d.metric ? ` after ${d.metric} ${d.before ?? ''}->${d.after ?? ''}` : ''}` }); else if (d.action === 'stop') out.push({ ...base, constraint: 'paused', reason: `${target.name} was stopped; outcome not recorded` }); else if (d.action === 'keep' && d.outcome === 'positive') out.push({ ...base, constraint: 'protect', reason: `operator kept ${target.name} after a positive outcome` }); else if (d.action === 'test' && d.outcome === 'negative') for (const [field, value] of Object.entries(d.params ?? {})) if (typeof value === 'number') out.push({ ...base, constraint: 'avoid_repeat', reason: `negative test on ${target.name}: ${field} ${value}`, field, value }); } return out; }
export function evaluate(ctx: OperatingContext, input: { targets?: string[]; proposal?: Proposal; history?: 'last'|'all'; brief?: boolean }) {
  const { resolved, unresolved } = scopeFor(ctx, input); const constraints = compileConstraints(ctx, resolved.length ? resolved : ctx.targets.filter(t => compileConstraints(ctx, [t]).length));
  if (!input.proposal) return { brand: ctx.brand, standing_constraints: constraints, unresolved_targets: unresolved };
  const scope = resolved.length ? resolved : ctx.targets.filter(t => compileConstraints(ctx, [t]).length);
  const rules = ctx.governance.filter(r => !r.superseded_by && (fields[r.action] in input.proposal! || r.action === 'claim' && ('claims' in input.proposal! || 'text' in input.proposal!) || r.effect === 'forbid' && r.applies_to?.some(x => scope.some(t => t.id === x || t.kind === x))));
  const requirements = rules.filter(r => r.effect === 'require'); const violations: any[] = []; const self_check: any[] = []; const pattern_hits: any[] = [];
  for (const r of rules) { const field = fields[r.action]; if (r.action === 'claim') { if (input.proposal.claims || input.proposal.text) self_check.push({ rule_id: r.id, object: r.object, detail: r.note || 'operator review required' }); for (const pattern of r.patterns ?? []) if (input.proposal.text) { const hit = input.proposal.text.match(new RegExp(pattern, 'i')); if (hit) pattern_hits.push({ rule_id: r.id, pattern, excerpt: hit[0] }); } continue; } if (!field || !(field in input.proposal)) continue; const actual = (input.proposal as any)[field]; if (r.action === 'send' && typeof actual === 'string' && r.applies_to?.includes(resolve(ctx.targets, actual)?.id ?? '') && r.effect === 'forbid') { violations.push({ rule_id: r.id, field, proposed: actual, detail: 'channel is forbidden' }); continue; } if (r.op && compare(r.op, r.value, actual) && r.effect === 'forbid') violations.push({ rule_id: r.id, field, proposed: actual, allowed: r.value, detail: `${field} violates ${r.op} ${JSON.stringify(r.value)}` }); if (!r.op && r.effect === 'forbid' && actual === true) violations.push({ rule_id: r.id, field, proposed: actual, allowed: false, detail: `${field} is forbidden` }); if (r.effect === 'require' && actual === false) violations.push({ rule_id: r.id, field, proposed: actual, allowed: true, detail: `${field} is required` }); }
  const conflicts: any[] = []; for (const c of constraints) { const target = scope.find(t => t.id === c.target); const touches = target && ((input.proposal.target && resolve(ctx.targets, input.proposal.target)?.id === target.id) || (input.proposal.channel && resolve(ctx.targets, input.proposal.channel)?.id === target.id) || (input.proposal.audience && resolve(ctx.targets, input.proposal.audience)?.id === target.id) || (!input.proposal.target && !input.proposal.channel && !input.proposal.audience && scope.includes(target))); if (!touches) continue; if ((c.constraint === 'no_start' || c.constraint === 'paused') && ['start','test'].includes(input.proposal.action ?? '')) conflicts.push({ target: c.target, constraint: c.constraint, decision_id: c.decision_id, detail: c.reason }); if (c.constraint === 'protect' && input.proposal.action === 'stop') conflicts.push({ target: c.target, constraint: c.constraint, decision_id: c.decision_id, detail: c.reason }); if (c.constraint === 'avoid_repeat' && typeof (input.proposal as any)[c.field] === 'number' && (input.proposal as any)[c.field] >= c.value) conflicts.push({ target: c.target, constraint: c.constraint, decision_id: c.decision_id, detail: `${c.field} ${(input.proposal as any)[c.field]} repeats a failed test at ${c.value}` }); }
  const pending = ctx.history.filter(d => d.status === 'proposed' && scope.some(t => t.id === d.target)); const verdict: 'ok'|'blocked'|'review' = violations.length ? 'blocked' : (conflicts.length || constraints.length || self_check.length || pattern_hits.length || unresolved.length || pending.length || !scope.length ? 'review' : 'ok');
  return { brand: ctx.brand, targets: resolved.length ? resolved : ctx.targets, unresolved_targets: unresolved, rules, requirements, standing_constraints: constraints, last_decisions: Object.fromEntries(scope.map(t => [t.id, ctx.history.filter(d => d.status === 'confirmed' && d.target === t.id).sort((a,b) => Date.parse(b.decided_at)-Date.parse(a.decided_at))[0] ?? null])), pending, violations, conflicts, self_check, pattern_hits, verdict, verdict_reason: `${verdict}${violations[0] ? `: ${violations[0].detail}` : ''}` };
}
