#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'; import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'; import { z } from 'zod'; import { ContextStore, StoreError, storeDirFromEnv } from './store.js'; import { evaluate } from './check.js';
const proposal=z.object({action:z.enum(['start','stop','change','test','keep','send','publish']).optional(),target:z.string().optional(),discount_pct:z.number().optional(),free_shipping:z.boolean().optional(),compare_at:z.boolean().optional(),guarantee:z.boolean().optional(),mentions_competitor:z.boolean().optional(),uses_ugc:z.boolean().optional(),audience:z.string().optional(),channel:z.string().optional(),claims:z.array(z.string()).optional(),text:z.string().optional()}).strict();
const checkInput=z.object({targets:z.array(z.string()).optional(),proposal:proposal.optional(),history:z.enum(['last','all']).optional(),brief:z.boolean().optional()}).strict();
const recordInput=z.object({action:z.enum(['start','stop','change','test','keep']),target:z.string(),outcome:z.enum(['pending','positive','negative','inconclusive']).default('pending'),metric:z.string().optional(),before:z.number().optional(),after:z.number().optional(),params:z.record(z.string(),z.union([z.number(),z.string(),z.boolean()])).optional(),note:z.string().max(200).optional(),actor:z.string().min(1)}).strict();
const result=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(x,null,2)}]});const error=(e:unknown)=>({isError:true,content:[{type:'text' as const,text:e instanceof Error?e.message:String(e)}]});
function createServer(store:ContextStore){const s=new McpServer({name:'ecom-context',version:'1.0.0'});s.registerTool('context.check',{title:'Check operating context',description:'Call once before you draft, recommend, or act. Pass the channels, offers, segments or products touched and what you propose. blocked means do not do it; review means show the operator conflicts before proceeding. Call again with a revised proposal if the verdict is not ok.',inputSchema:checkInput.shape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async input=>{try{return result(evaluate(store.load(),input));}catch(e){return error(e);}});s.registerTool('history.record',{title:'Record a decision',description:'Record a decision the operator made or confirmed in this conversation. It is proposed until the operator confirms it. Do not record your own recommendation.',inputSchema:recordInput.shape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},async input=>{try{const d=store.record(input);return result({recorded:d,confirm:`Confirm with: ecom-context confirm ${d.id}`});}catch(e){return error(e);}});return s;}
async function cli(store:ContextStore,args:string[]){if(args[0]==='init'){store.ensure();const {writeFileSync}=await import('node:fs');const {join}=await import('node:path');writeFileSync(join(store.dir,'brand.md'),'Describe this brand, products, and audience.\n');writeFileSync(join(store.dir,'targets.json'),'{"targets":[]}\n');writeFileSync(join(store.dir,'governance.json'),'{"rules":[]}\n');writeFileSync(join(store.dir,'history.json'),'{"decisions":[]}\n');console.log(`initialized ${store.dir}`);return;}const ctx=store.load();if(args[0]==='validate'){console.log('valid');return;}if(args[0]==='compile'){console.log(JSON.stringify(evaluate(ctx,{}),null,2));return;}if(args[0]==='confirm'){store.confirm(args[1]);console.log('confirmed');return;}if(args[0]==='reject'){store.reject(args[1]);console.log('rejected');return;}if(args[0]==='check'){const input=JSON.parse(args[1]||'{}');const out=evaluate(ctx,input);console.log(JSON.stringify(out,null,2));process.exitCode=out.verdict==='blocked'?2:out.verdict==='review'?1:0;return;}throw new StoreError('usage: ecom-context init|validate|compile|confirm|reject|check <json>');}
async function main(){const store=new ContextStore(storeDirFromEnv());if(process.argv[2]){await cli(store,process.argv.slice(2));return;}store.ensure();const s=createServer(store);await s.connect(new StdioServerTransport());console.error(`ecom-context MCP server on stdio (store=${store.dir})`);}main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exit(1);});
