import { mkdirSync, readFileSync, renameSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path'; import { randomUUID } from 'node:crypto'; import { ZodError } from 'zod';
import { Decision, GovernanceFile, HistoryFile, TargetsFile, type Decision as DecisionType, type OperatingContext, type Target } from './types.js';
export class StoreError extends Error { constructor(message:string){super(message);this.name='StoreError';} }
const CAP=4096;
function read(path:string):unknown{try{return JSON.parse(readFileSync(path,'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return null;if(e instanceof SyntaxError)throw new StoreError(`${path} is not valid JSON. Fix it by hand and try again.`);throw e;}}
function parse<T>(path:string,schema:{parse(v:unknown):T},empty:T):T{const raw=read(path);if(raw===null)return empty;try{return schema.parse(raw);}catch(e){if(e instanceof ZodError)throw new StoreError(`${path} is not a valid typed store (${e.issues.map(i=>`${i.path.join('.')||'(root)'}: ${i.message}`).join('; ')}).`);throw e;}}
function write(path:string,data:unknown){const tmp=`${path}.${process.pid}.tmp`;writeFileSync(tmp,`${JSON.stringify(data,null,2)}\n`);renameSync(tmp,path);}
export class ContextStore { constructor(readonly dir:string){} ensure(){mkdirSync(this.dir,{recursive:true});const brand=join(this.dir,'brand.md');if(existsSync(brand)&&readFileSync(brand).byteLength>CAP)throw new StoreError('brand.md exceeds the 4,096-byte cap; put longer material in a document.');for(const old of ['memory.json','channels.json'])if(existsSync(join(this.dir,old)))throw new StoreError(`${old} is removed in v1; run ecom-context migrate.`);} load():OperatingContext{this.ensure();return{brand:existsSync(join(this.dir,'brand.md'))?readFileSync(join(this.dir,'brand.md'),'utf8'):'',targets:parse(join(this.dir,'targets.json'),TargetsFile,{targets:[]}).targets,governance:parse(join(this.dir,'governance.json'),GovernanceFile,{rules:[]}).rules,history:parse(join(this.dir,'history.json'),HistoryFile,{decisions:[]}).decisions};} record(input:Omit<DecisionType,'id'|'decided_at'|'status'|'recorded_by'>):DecisionType{const ctx=this.load();const target=resolve(ctx.targets,input.target);if(!target)throw new StoreError(`target '${input.target}' does not resolve; use a registry id, name or alias.`);const d=Decision.parse({...input,id:`dec_${randomUUID()}`,decided_at:new Date().toISOString(),status:'proposed',recorded_by:'agent',target:target.id});write(join(this.dir,'history.json'),{decisions:[...ctx.history,d]});return d;}}
export function resolve(targets:Target[],query:string):Target|undefined{const q=query.toLowerCase();return targets.find(t=>t.id.toLowerCase()===q||t.name.toLowerCase()===q||t.aliases.some(a=>a.toLowerCase()===q));}
export function storeDirFromEnv(env:NodeJS.ProcessEnv=process.env,cwd=process.cwd()){return env.ECOM_CONTEXT_STORE?.trim()||join(cwd,'store');}
